create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  content text not null default '',
  images jsonb not null default '[]'::jsonb,
  likes integer not null default 0,
  timestamp timestamptz not null default now()
);

create or replace function public.increment_post_likes(target_post_id bigint)
returns integer
language plpgsql
as $$
declare
  updated_likes integer;
begin
  update public.posts
  set likes = likes + 1
  where id = target_post_id
  returning likes into updated_likes;

  return updated_likes;
end;
$$;
